### PR TITLE
navbar added

### PR DESCRIPTION
**Pull request by Ganther3301**

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
Can you send me a screenshot of the application when applicable.

**Comment by Ganther3301** [comment]
> Can you send me a screenshot of the application when applicable.

Screenshot from 2022-10-22 02-37-37

hey so i modified it a bit more. should i create another pull request?

**Comment by Mohamed-Ayaan358** [comment]
Ya this is good apply it to the others and we will convene to select your marks.

**Comment by Mohamed-Ayaan358** [comment]
Send screenshots or video

**Comment by Ganther3301** [comment]
hey i'm done. this is the last commit
Screenshot from 2022-10-22 03-25-56

**Comment by Mohamed-Ayaan358** [comment]
!bounty 40

**Comment by NavinShrinivas** [comment]
!bounty 30

**Pull request merged**
