### PR TITLE
PES2UG21CS031 aditi

### PR DESCRIPTION
**Pull request by Aditikhasnis**
added 2 new arguments ..in pointLight

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
can u send me a screenshot of the final view? And what issue this relates to?

**Comment by Mohamed-Ayaan358** [comment]
Excuse me @Aditikhasnis but i do not exactly understand what you have done with this code

**Comment by Aditikhasnis** [comment]
actually its not reflecting anything in final view

**Comment by Mohamed-Ayaan358** [comment]
Have u installed three.js?

**Comment by Aditikhasnis** [comment]
2 other parameters that added in 47th line of PointLight ...is it basically to increase the intensity

**Comment by Aditikhasnis** [comment]
no i havent installed three.js

**Comment by Mohamed-Ayaan358** [comment]
@Aditikhasnis this is what the site actually looks like
image

**Comment by Mohamed-Ayaan358** [comment]
do install it

**Comment by Aditikhasnis** [comment]
ok ...i will ......i get back to u in some time

**Pull request closed without merging**
