### PR TITLE
added navbar

### PR DESCRIPTION
**Pull request by PavvanPradeep**
added a navbar and used a space theme

### CODE REVIEW

**Comment by Mohamed-Ayaan358** [comment]
can u give me a screenshot to previews

**Comment by PavvanPradeep** [comment]
@Mohamed-Ayaan358 where do i upload it?

**Comment by PavvanPradeep** [comment]
also can i add a footer to it with contact info and stuff. could you approve my issue

**Comment by Mohamed-Ayaan358** [comment]
Well the navbar is allright, but why did you remove the background of the entire website?

**Comment by PavvanPradeep** [comment]
@Mohamed-Ayaan358 oh my bad so can i add the color and submit again?

**Comment by PavvanPradeep** [comment]
@Mohamed-Ayaan358 theres no color in the inital build should i just add one

**Comment by Mohamed-Ayaan358** [comment]
This is what it looks like
image

**Comment by PavvanPradeep** [comment]
@Mohamed-Ayaan358 Lmao i did not do that. i dont even have that image

**Comment by PavvanPradeep** [comment]
Screenshot 2022-10-21 at 11 45 18 PM

**Comment by Mohamed-Ayaan358** [comment]
Im sorry I cant accept that

**Comment by PavvanPradeep** [comment]
fine i'll rework on that

**Pull request closed without merging**
